### ISSUE TITLE
Performance: limit the number of inspected commits

### ISSUE THREAD

**Issue by oleg-vinted** [kaihendry/lesshero#6]
Inspecting huge repositories takes a long time. In this case we could probably inspect only the latest N commits, or last N months worth of commits. 🤔

**Comment by kaihendry** [comment]
Yes! The performance sucks and sadly I can't make it concurrent since the underlying library isn't thread safe. 🥹

https://github.com/go-git/go-git/issues/48#issuecomment-1263107209

Good idea to limit the last number of commits. How about you try make a PR? :P

**Comment by kaihendry** [comment]
performance is satisfactory now
